#!/bin/bash

usage ()
{
  echo "Usage: rpi-cluster [OPTIONS] COMMAND [arg...]"
  echo "       rpi-cluster [ --help | -v | --version ]"
  echo ""
  echo "Utility script to manage Kubernetes on a Raspberry Pi Cluster."
  echo ""
  echo "Options:"
  echo ""
  echo "  -h, --help          Print usage"
  echo "  -v, --version       Print version information"
  echo ""
  echo "Commands:"
  echo ""
  echo "  Host System:"
  echo "    flash             Flash SD card with a Raspberry Pi image"
  echo "    download          Download and extract Kubernetes"
  echo "    install-client    Install Kubernetes Client"
  echo "    uninstall-client  Remove Kubernetes from Client"
  echo ""
  echo "  Raspberry Pi 3:"
  echo "    download          Download and axtract Kubernetes"
  echo "    install-server    Install Kubernetes server"
  echo "    enable-master     Enables Kubernetes master node"
  echo "    enable-worker     Enables Kubernetes worker node"
  echo "    pull              Pull container images"
  echo "    disable           Disables Kubernetes on this node"
  echo "    uninstall-server  Remove Kubernetes from this node"
  echo ""
  echo "  Helper Functions:"
  echo "    status            System Status"
  echo "    clean             Cleans the directory and resets to original state"
  echo ""

  exit
}

if [[ $# < 1 ]]; then
  usage
fi

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

BASEDIR=$(dirname "$0")
source $BASEDIR/scripts/util.sh

case "$1" in
  flash)             source $BASEDIR/scripts/flash.sh;;
  install-client)    source $BASEDIR/scripts/install-client.sh;; 
  install-server)    source $BASEDIR/scripts/install-server.sh;;
  enable-master)     source $BASEDIR/scripts/enable-master.sh;;
  enable-worker)     source $BASEDIR/scripts/enable-worker.sh;;
  pull)              source $BASEDIR/scripts/pull.sh;;
  disable)           source $BASEDIR/scripts/disable.sh;; 
  uninstall-client)  source $BASEDIR/scripts/uninstall-client.sh;; 
  uninstall-server)  source $BASEDIR/scripts/uninstall-server.sh;;
  status)            source $BASEDIR/scripts/status.sh;;
  download)          source $BASEDIR/scripts/download.sh;;  
  clean)             source $BASEDIR/scripts/clean.sh;;
  -h | --help)       usage;;
  -v | --version)    source $BASEDIR/scripts/version.sh;;
  *)                 usage;;
esac

shift

mkdir -p ${BASEDIR}/logs

exec-command $@
