#!/bin/bash

usage ()
{
  echo "Usage: rpi-cluster [OPTIONS] COMMAND [arg...]"
  echo "       rpi-cluster [ --help | -v | --version ]"
  echo ""
  echo "Utility script to manage Kubernetes on a Raspberry Pi Cluster."
  echo ""
  echo "Options:"
  echo ""
  echo "  -h, --help        Print usage"
  echo "  -v, --version     Print version information and quit"
  echo ""
  echo "Commands:"
  echo ""
  echo "  Host System:"
  echo "    flash           Flash SD card with a Raspberry Pi Image"
  echo ""
  echo "  Raspberry Pi 3:"
  echo "    install         Install Kubernetes"
  echo "    enable-master   Enables Kubernetes Master Node"
  echo "    enable-worker   Enables Kubernetes Worker Node"
  echo "    pull            Pull container images"
  echo "    disable         Disables Kubernetes on this node"
  echo "    uninstall       Removes Kubernetes from this node"
  echo ""
  echo "  Helper Functions:"
  echo "    status          Installation status"
  echo "    clean           Cleans the directory and resets to original state"
  echo "    download        Download Kubernetes"
  echo ""

  exit
}

if [[ $# < 1 ]]; then
  usage
fi

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

BASEDIR=$(dirname "$0")
source $BASEDIR/scripts/util.sh

case "$1" in
  flash)           source $BASEDIR/scripts/flash.sh;;
  install)         source $BASEDIR/scripts/install.sh;; 
  enable-master)   source $BASEDIR/scripts/enable-master.sh;;
  enable-worker)   source $BASEDIR/scripts/enable-worker.sh;;
  pull)            source $BASEDIR/scripts/pull.sh;;
  disable)         source $BASEDIR/scripts/disable.sh;; 
  uninstall)       source $BASEDIR/scripts/uninstall.sh;; 
  status)          source $BASEDIR/scripts/status.sh;;
  download)        source $BASEDIR/scripts/download.sh;;  
  clean)           source $BASEDIR/scripts/clean.sh;;
  -h | --help)     usage;;
  -v | --version)  source $BASEDIR/scripts/version.sh;;
  *)               usage;;
esac

shift

mkdir -p ${BASEDIR}/logs

exec-command $@
