apiVersion: v1
kind: Pod
metadata:
  name: kube-system
spec:
  hostNetwork: true
  containers:
    - name: "kube-proxy"
      image: "hyperkube"
      args:
        - "/hyperkube"
        - "proxy"
        - "--master=http://rpi-master:8080"
        - "--v=2"
      securityContext:
        privileged: true
